var express = require('express');
var router = express.Router();


const datalist = [
  { 'id': 1, 'term': "CI/CD", 'description':"In CI, work completed by the developers is merged frequently into the main branch, rather than waiting until the end of the day or until the end of the sprint. This practice of merging fewer changes at a time allows developers to resolve merge conflicts earlier and address regression defects more efficiently and quickly.", 'Reference':"P.P. Dingare, CI/CD pipeline using Jenkins Unleashed: solutions while setting up CI/CD processes, Apress L.P., 2022. " },
  { 'id': 2, 'term': "Chaos Engineering", 'description':"The identification of security control failures through proactive experimentation to build confidence in the system’s ability to defend against malicious conditions in production", 'Reference':"Aaron Rinehart, “Security Chaos Engineering: A New Paradigm for Cybersecurity,” Opensource.com, January 24, 2018," },
  { 'id': 3, 'term': "Application Release Automation(ARA)", 'description':"Application release automation (ARA) is a process that automatically packages and deploys an application, or application updates, through the stages of development to production. To do this, ARA software features include deployment automation, release coordination, and environment management and modeling tools", 'Reference':" A. S. Gillis, “What is Application Release Automation (ARA)?: Definition from TechTarget,” IT Operations, https://www.techtarget.com/searchitoperations/definition/application-release-automation-ARA [accessed Jul. 19, 2023]. " },
  { 'id': 4, 'term': "Containers", 'description':"Containers also provide a virtual environment that packages the application processes, metadata, and file system—everything that is required by an application to run.", 'Reference':"P.S. Kocher, Microservices and Containers, Addison-Wesley, 2018. [Online]. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4087635&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 5, 'term': "Docker", 'description':"Docker is a tool that promises to easily encapsulate the process of creating a distributable artifact for any application, deploying it at scale into any environment, and streamlining the workflow and responsiveness of agile software organizations.", 'Reference':"K. Matthias, Docker: Up and Running, First edition, Edited by S.P. Kane, O’Reilly, 2015. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4062596&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 6, 'term': "GitOps", 'description':"GitOps is a framework to automate infrastructure processes using DevOps tools and concepts. With version control you can manage infrastructure and environment definitions with existing tooling.", 'Reference':"N. Vinto and A. Soto Bueno, GitOps Cookbook: Kubernetes Automation in Practice, First edition, O'Reilly Media, 2023. [Online]. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b5084939&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 7, 'term': "Infrastructure as a Code", 'description':"Infrastructure as code (IaC) uses DevOps methodology and versioning with a descriptive model to define and deploy infrastructure, such as networks, virtual machines, load balancers, and connection topologies.", 'Reference':"jacob m, juliakm, thepet v, and Kaim Ed, What is infrastructure as a Code (IaC), Microsoft Learn AI Skills Challenge,https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code,[Accesses: July 17, 2023]" },
  { 'id': 8, 'term': "Platform Engineering", 'description':"Platform engineering is the discipline of designing and building toolchains and workflows that enable self-service capabilities for software engineering organizations in the cloud-native era", 'Reference':"Luca Galante, What is Platform Engineering, Platform Engineering, https://platformengineering.org/blog/what-is-platform-engineering,[Accessed July 20, 2023] " },
  { 'id': 9, 'term': "version control", 'description':"A version control system records changes to files stored in the system. These files can be source code, assets, or other documents that might be part of a software development project.", 'Reference':"Google cloud, DevOps Tech: Version Control, GoogleCloud.org, https://cloud.google.com/architecture/devops/devops-tech-version-control#:~:text=A%20version%20control%20system%20records,groups%20called%20commits%20or%20revisions.[Accessed July 16,2023] " },
  { 'id': 10, 'term': "Tenant", 'description':"A tenant is a group of users who share a common access with specific privileges to the software instance.", 'Reference':"Rajesh Kumar, What is tenant, Devops School, https://www.devopsschool.com/blog/what-is-a-tenant-multi-tenant-in-computing-and-software-domain/#:~:text=A%20tenant%20is%20a%20group,is%20known%20as%20a%20tenant.[Accessed July 19, 2023]" },

]

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Software Development', name: datalist });
});

module.exports = router;
