var express = require('express');
var router = express.Router();


const datalist = [
  { 'id': 1, 'term': "CI/CD", 'description':"In CI, work completed by the developers is merged frequently into the main branch, rather than waiting until the end of the day or until the end of the sprint. This practice of merging fewer changes at a time allows developers to resolve merge conflicts earlier and address regression defects more efficiently and quickly.", 'Reference':"P.P. Dingare, CI/CD pipeline using Jenkins Unleashed: solutions while setting up CI/CD processes, Apress L.P., 2022. " },
  { 'id': 2, 'term': "Chaos Engineering", 'description':"The identification of security control failures through proactive experimentation to build confidence in the system’s ability to defend against malicious conditions in production", 'Reference':"Aaron Rinehart, “Security Chaos Engineering: A New Paradigm for Cybersecurity,” Opensource.com, January 24, 2018," },
  { 'id': 3, 'term': "Application Release Automation(ARA)", 'description':"Application release automation (ARA) is a process that automatically packages and deploys an application, or application updates, through the stages of development to production. To do this, ARA software features include deployment automation, release coordination, and environment management and modeling tools", 'Reference':" A. S. Gillis, “What is Application Release Automation (ARA)?: Definition from TechTarget,” IT Operations, https://www.techtarget.com/searchitoperations/definition/application-release-automation-ARA [accessed Jul. 19, 2023]. " },
  { 'id': 4, 'term': "Containers", 'description':"Containers also provide a virtual environment that packages the application processes, metadata, and file system—everything that is required by an application to run.", 'Reference':"P.S. Kocher, Microservices and Containers, Addison-Wesley, 2018. [Online]. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4087635&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 5, 'term': "Docker", 'description':"Docker is a tool that promises to easily encapsulate the process of creating a distributable artifact for any application, deploying it at scale into any environment, and streamlining the workflow and responsiveness of agile software organizations.", 'Reference':"K. Matthias, Docker: Up and Running, First edition, Edited by S.P. Kane, O’Reilly, 2015. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b4062596&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 6, 'term': "GitOps", 'description':"GitOps is a framework to automate infrastructure processes using DevOps tools and concepts. With version control you can manage infrastructure and environment definitions with existing tooling.", 'Reference':"N. Vinto and A. Soto Bueno, GitOps Cookbook: Kubernetes Automation in Practice, First edition, O'Reilly Media, 2023. [Online]. Available: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b5084939&site=eds-live&scope=site. [Accessed: July 19, 2023]." },
  { 'id': 7, 'term': "Infrastructure as a Code", 'description':"Infrastructure as code (IaC) uses DevOps methodology and versioning with a descriptive model to define and deploy infrastructure, such as networks, virtual machines, load balancers, and connection topologies.", 'Reference':"jacob m, juliakm, thepet v, and Kaim Ed, What is infrastructure as a Code (IaC), Microsoft Learn AI Skills Challenge,https://learn.microsoft.com/en-us/devops/deliver/what-is-infrastructure-as-code,[Accesses: July 17, 2023]" },
  { 'id': 8, 'term': "Platform Engineering", 'description':"Platform engineering is the discipline of designing and building toolchains and workflows that enable self-service capabilities for software engineering organizations in the cloud-native era", 'Reference':"Luca Galante, What is Platform Engineering, Platform Engineering, https://platformengineering.org/blog/what-is-platform-engineering,[Accessed July 20, 2023] " },
  { 'id': 9, 'term': "version control", 'description':"A version control system records changes to files stored in the system. These files can be source code, assets, or other documents that might be part of a software development project.", 'Reference':"Google cloud, DevOps Tech: Version Control, GoogleCloud.org, https://cloud.google.com/architecture/devops/devops-tech-version-control#:~:text=A%20version%20control%20system%20records,groups%20called%20commits%20or%20revisions.[Accessed July 16,2023] " },
  { 'id': 10, 'term': "Tenant", 'description':"A tenant is a group of users who share a common access with specific privileges to the software instance.", 'Reference':"Rajesh Kumar, What is tenant, Devops School, https://www.devopsschool.com/blog/what-is-a-tenant-multi-tenant-in-computing-and-software-domain/#:~:text=A%20tenant%20is%20a%20group,is%20known%20as%20a%20tenant.[Accessed July 19, 2023]" },
  { 'id': 11, 'term': "Branching", 'description': "Branching occurs when an object under review in source control is duplicated so that other developers can work on it concurrently.", 'Reference':"Valerii G. Grytsenko and Oksana M. Podolyan, 2014. 'Application of Git-Branching for the Organization of Teamwork on IT Projects', Information Technologies and Learning Tools, 39(1), pp. 250–263. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=edsdoj&AN=edsdoj.1556c992934748f9ac3a618510d42c1c&site=eds-live&scope=site [Accessed: 4 August 2023]."},
  { 'id': 12, 'term': "Agile Software Development", 'description':"A lightweight framework that promotes iterative development and incremental delivery using self-organizing cross-functional teams.", 'Reference':"Stober, T. and Hansmann, U.  Agile software development : best practices for large software development projects. Springer.(2009), Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b2620092&site=eds-live&scope=site [Accessed: 4 August 2023]."},
  { 'id': 13, 'term': "Clusters", 'description':"A set of connected computers that work together to enable load balancing, auto scaling and high availability.", 'Reference':"Farcic, V. (2018) The DevOps 2.2 Toolkit : Self-Sufficient Docker Clusters. Packt Publishing. Available at: https://search.ebscohost.com/login.aspx?direct=true&db=cat00097a&AN=deakin.b5181845&site=eds-live&scope=site (Accessed: 4 August 2023)."},
  { 'id': 14, 'term': "Containers-as-a-Service (CaaS)", 'description':"A cloud service model that offers container-based virtualization with container engines, orchestration and compute resources", 'Reference':"Mohamed K. Hussein, Mohamed H. Mousa and Mohamed A. Alqarni (2019) ‘A placement architecture for a container as a service (CaaS) in a cloud environment’, Journal of Cloud Computing: Advances, Systems and Applications, 8(1), pp. 1–15. doi:10.1186/s13677-019-0131-1.[Accessed: 4 August 2023"},
  { 'id': 15, 'term': "Integration Testing", 'description':"The testing of a component or module of code to ensure it integrates correctly with other components or modules of code.", 'Reference':"Jin Li et al. (2018) ‘An integration testing framework and evaluation metric for vulnerability mining methods’, China Communications, Communications, China, China Commun, 15(2), pp. 190–208. doi:10.1109/CC.2018.8300281.[Accessed: 5 August 2023"},
  { 'id': 16, 'term': "Mean Time to Recovery (MTTR)", 'description':"MTTR is the average time that a device will take to recover from a failure, i.e. going from “down” to “available”.", 'Reference':"Alex Circei, Mean Time To Recovery—A DORA Metric Explained,Forbes, Apr 4, 2023, Available: https://www.forbes.com/sites/theyec/2023/04/04/mean-time-to-recovery-a-dora-metric-explained/?sh=4fa92b1a60b4.[Accessed: 5 August 2023]"},
  { 'id': 17, 'term': "Production", 'description':"Production, also known as live, is an environment where the application or feature is accessible to users.", 'Reference':"Hoffmann, A. et al. (2001) ‘Generating production quality software development tools using a machine description language’, Proceedings Design, Automation and Test in Europe. Conference and Exhibition 2001, Design, Automation and Test in Europe, 2001. Conference and Exhibition 2001. Proceedings, Design, automation and test in Europe, pp. 674–678. doi:10.1109/DATE.2001.915097.[Accessed: 5 August 2023]"},
  { 'id': 18, 'term': "Rollback", 'description':"The process of returning a product or application back to a previous version. Usually this is done when the current version experiences problems or issues.", 'Reference':"Sathre, J. and Zambreno, J. (2023) ‘Automated software attack recovery using rollback and huddle’, Design Automation for Embedded Systems, (Preprints), pp. 1–18. doi:10.1007/s10617-008-9020-4.[Accessed: 8 August 2023]"},
  { 'id': 19, 'term': "Staging Environment", 'description':"A staging environment (stage) is a nearly exact replica of a production environment for software testing. Staging environments are made to test codes, builds, and updates to ensure quality under a production-like environment before application deployment.", 'Reference':"Alexander S. Gillis, staging environment, TechTarget,2018, Available: https://www.techtarget.com/searchsoftwarequality/definition/staging-environment#:~:text=A%20staging%20environment%20(stage)%20is,like%20environment%20before%20application%20deployment.[Accessed: 5 August 2023]"},
  { 'id': 20, 'term': "User Acceptance Testing (UAT)", 'description':"A type of software testing that verifies that a given application works for the user. During this process, actual users test the software to make sure it behaves as expected in real-world scenarios.", 'Reference':"Gordon, S. et al.  ‘Best Practice Recommendations: User Acceptance Testing for Systems Designed to Collect Clinical Outcome Assessment Data Electronically’, Therapeutic Innovation & Regulatory Science, ,(2022)56(3), pp. 442–453. doi:10.1007/s43441-021-00363-z.[Accessed: 5 August 2023]"}

]

/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'SIT722 Software Development', name: datalist });
});

module.exports = router;
